function SubjectFilter(data,subj) % Function to remove a particular subject
A=readtable(data);
Session=table2array(A(:,{'subj_idx'}));
RC=table2array(A(:,{'RC'}));
Cat1=table2array(A(:,{'Cat1'}));
Cat2=table2array(A(:,{'Cat2'}));
RT=table2array(A(:,{'rt'}));
MC=table2array(A(:,{'MC'}));
LT=table2array(A(:,{'LT'}));
JP=table2array(A(:,{'JP'}));
AD=table2array(A(:,{'AD'}));
Volume=table2array(A(:,10));
response=table2array(A(:,{'response'}));
Idx=unique(Session);
IDX=Session~=subj;
subj_idx=Session(IDX);
RCR=RC(IDX);
Cat1R=Cat1(IDX);
Cat2R=Cat2(IDX);
RTR=RT(IDX);
MCR=MC(IDX);
LTR=LT(IDX);
JPR=JP(IDX);
ADR=AD(IDX);
VolumeR=Volume(IDX);
responseR=response(IDX);
Total=table(subj_idx,RCR,Cat1R,Cat2R,RTR,MCR,LTR,JPR,ADR,VolumeR,responseR);
Total.Properties.VariableNames={'subj_idx','RC','Cat1','Cat2','rt','MC','LT','JP','AD','Volume(%)','response'};
OFname='Latest_RTFiltered_PlaceboSampleData2Categorywith5050trials'+string(subj)+'_removed.csv';
writetable(Total,OFname);
end

