function Y35050Filter(data,OFname) % Function to remove 50:50 or Y3 trials
A=readtable(data);
Session=table2array(A(:,{'subj_idx'}));
TrialNum=table2array(A(:,{'Trial_Number'}));
RC=table2array(A(:,{'RC'}));
Cat1=table2array(A(:,{'Cat1'}));
Cat2=table2array(A(:,{'Cat2'}));
RT=table2array(A(:,{'RT'}));
MC=table2array(A(:,{'MC'}));
LT=table2array(A(:,{'LT'}));
JP=table2array(A(:,{'JP'}));
AD=table2array(A(:,{'AD'}));
Volume=table2array(A(:,{'Volume___'}));
response=table2array(A(:,{'response'}));
Idx=unique(Session);
IDX=response~=0.5;
subj_idx=Session(IDX);
TRNUMBER=TrialNum(IDX);
RCR=RC(IDX);
Cat1R=Cat1(IDX);
Cat2R=Cat2(IDX);
RTR=RT(IDX);
MCR=MC(IDX);
LTR=LT(IDX);
JPR=JP(IDX);
ADR=AD(IDX);
VolumeR=Volume(IDX);
responseR=response(IDX);
Total=table(subj_idx,TRNUMBER,RCR,Cat1R,Cat2R,RTR,MCR,LTR,JPR,ADR,VolumeR,responseR);
Total.Properties.VariableNames={'subj_idx','Trial_Number','RC','Cat1','Cat2','RT','MC','LT','JP','AD','Volume(%)','response'};
writetable(Total,OFname);
end

